framework: jest
postMerge:
  pattern:
    - "./tests/*.test.ts"
preMerge:
  pattern:
    - "./tests/*.test.ts"
preRun:
     command:
        - yarn install
        - yarn run prepare
postRun:
     command:
        - yarn --version
version: 1.0
